Repository LittleClumsy/ToDo_CLI, pull requests merged in 2023-05, with the labels that each got.

#55 MISC Files Docs
  .gitignore
  Makefile
  Pipfile.lock
  VERSION
  docs/README.md
  docs/misc/ignore.md
  docs/misc/make.md
  docs/misc/pipenv.md
  docs/misc/requirements.md
  docs/misc/sonar.md
  docs/misc/version.md
  requirements.txt
  sonar-project.properties
Labels: documentation

#57 Changed tasks file logic - todo.py refactoring - docs
  .github/workflows/ubuntu_pipeline.yml
  Makefile
  docs/README.md
  docs/misc/exit_codes.md
  docs/source/cli_controller.md
  docs/source/config_controller.md
  docs/source/install_helper.md
  docs/source/logger.md
  docs/source/main.md
  tests/unit/test_cli_controller.py
  tests/unit/test_config.py
  tests/unit/test_helpers.py
  tests/unit/test_install_helper.py
  todo.py
  todo_cli/config/config_controller.py
  todo_cli/helpers/install_helper.py
  todo_cli/helpers/tasks_helper.py
Labels: documentation, enhancement

#60 Config Controller Update
  docs/README.md
  docs/source/config_controller.md
  docs/source/json_helper.md
  docs/source/os_helper.md
  tests/unit/test_config.py
  tests/unit/test_install_helper.py
  todo.py
  todo_cli/config/config_controller.py
Labels: documentation, enhancement

#64 Try out some new sonar tags
  README.md
Labels: documentation

#66 Added pyinstaller to packages
  .github/workflows/ubuntu_pipeline.yml
  Makefile
  Pipfile
  Pipfile.lock
Labels: enhancement

#68 Create Pipelines.md
  docs/README.md
  docs/misc/Pipelines.md
Labels: documentation

#65 Updated JSON Helper and all connected files + Added new exit code
  .gitignore
  Makefile
  docs/README.md
  docs/misc/exit_codes.md
  docs/source/config_controller.md
  docs/source/error.md
  docs/source/json_helper.md
  docs/source/main.md
  requirements.txt
  tests/data/string_in.json
  tests/unit/test_config_controller.py
  tests/unit/test_error.py
  tests/unit/test_json_helper.py
  todo.py
  todo_cli/config/config_controller.py
  todo_cli/err/__init__.py
  todo_cli/err/error.py
  todo_cli/helpers/json_helper.py
Labels: documentation, enhancement
